/**
 * Borrower Copilot - Adaptive Question Tree
 * Defines 9 must questions and 11 additional questions with applicability predicates.
 * Pure definitions without React dependencies.
 */

import { BorrowerProfile } from './schema';

export interface QuestionDefinition {
  id: string;
  isMust: boolean;
  title: string;
  subtitle: string;
  field: keyof BorrowerProfile | string;
  category: 'core' | 'income' | 'obligations' | 'risk_proxies' | 'assets' | 'quotes';
  type: 'select' | 'number' | 'range' | 'boolean' | 'radio';
  options?: { label: string; value: any; hint?: string }[];
  min?: number;
  max?: number;
  step?: number;
  placeholder?: string;
  suffix?: string;
  isVisible: (profile: Partial<BorrowerProfile>) => boolean;
  whyAsked: string;
  whatItMoves: string;
}

export const QUESTIONS_LIST: QuestionDefinition[] = [
  // ---------------------------------------------------------
  // 9 MUST QUESTIONS (Minimum set to compute wide-band output)
  // ---------------------------------------------------------
  {
    id: 'q1_purpose',
    isMust: true,
    title: 'What is the purpose of this loan?',
    subtitle: 'Lenders evaluate productive and asset-backed purposes differently from discretionary consumption.',
    field: 'purpose',
    category: 'core',
    type: 'select',
    options: [
      { label: 'Personal Vehicle / Two-Wheeler', value: 'personal_vehicle', hint: 'Vehicle hypothecation' },
      { label: 'Home Purchase / Renovation', value: 'home', hint: 'Long tenure, property mortgage' },
      { label: 'Business Stock or Equipment', value: 'business_stock_equipment', hint: 'Productive capital expenditure' },
      { label: 'Commercial Vehicle / Delivery Fleet', value: 'commercial_vehicle', hint: 'Income-generating asset' },
      { label: 'Debt Consolidation', value: 'debt_consolidation', hint: 'Paying off high-cost credit' },
      { label: 'Higher Education', value: 'education', hint: 'Productive human capital' },
      { label: 'Medical Emergency', value: 'medical', hint: 'Immediate essential need' },
      { label: 'Wedding / Discretionary', value: 'wedding_discretionary', hint: 'Unsecured personal consumption' },
      { label: 'Other Personal Need', value: 'other', hint: 'Standard personal loan' },
    ],
    isVisible: () => true,
    whyAsked: 'Determines product routing, legal collateral expectations, and repayment risk category.',
    whatItMoves: 'O1 (Verdict decision tree), O3 (Product rate spread)',
  },
  {
    id: 'q2_amount_wanted',
    isMust: true,
    title: 'How much capital do you want to borrow?',
    subtitle: 'State the exact ticket size you have in mind before lender haircuts.',
    field: 'amountWanted',
    category: 'core',
    type: 'number',
    min: 10000,
    max: 20000000,
    step: 5000,
    placeholder: 'e.g. 800000',
    suffix: 'INR',
    isVisible: () => true,
    whyAsked: 'Your request is compared against safe capacity to see if borrowing less is needed.',
    whatItMoves: 'O1 (Verdict compared against safe amount), O4 (Baseline EMI)',
  },
  {
    id: 'q3_employment_type',
    isMust: true,
    title: 'What is your primary employment or business type?',
    subtitle: 'Income verification standards and baseline FOIR caps differ by stability tier.',
    field: 'employmentType',
    category: 'income',
    type: 'radio',
    options: [
      { label: 'Salaried Professional', value: 'salaried', hint: 'Regular monthly payslip and bank transfer' },
      { label: 'Self-Employed (Formal with ITR)', value: 'self_employed_formal', hint: 'Filed Income Tax Returns + business cashflows' },
      { label: 'Informal / Gig Worker (No ITR)', value: 'informal_gig', hint: 'Cash earnings, daily contracts, or platform payouts' },
    ],
    isVisible: () => true,
    whyAsked: 'Establishes the underwriting model, applicable documentation haircut, and FOIR tier.',
    whatItMoves: 'O2 (FOIR cap baseline, income assessment formula), O3 (Risk tier)',
  },
  {
    id: 'q4_income',
    isMust: true,
    title: 'What is your net monthly take-home income?',
    subtitle: 'For salaried: your take-home payslip amount. For businesses/informal: your net cash generated after business expenses.',
    field: 'netMonthlyIncome',
    category: 'income',
    type: 'number',
    min: 5000,
    max: 2000000,
    step: 1000,
    placeholder: 'e.g. 110000',
    suffix: 'INR / month',
    isVisible: () => true,
    whyAsked: 'The fundamental anchor for FOIR ceilings and residual living buffer.',
    whatItMoves: 'O2 (Maximum amount), O4 (Safe monthly payment)',
  },
  {
    id: 'q5_years_experience',
    isMust: true,
    title: 'How long have you been in this current job or business?',
    subtitle: 'Stability demonstrates consistency through economic fluctuations.',
    field: 'yearsInJobOrBusiness',
    category: 'income',
    type: 'number',
    min: 0,
    max: 50,
    step: 1,
    placeholder: 'e.g. 5',
    suffix: 'Years',
    isVisible: () => true,
    whyAsked: 'Over 3 years of stability qualifies for interest rate discounts up to 50 bps.',
    whatItMoves: 'O3 (Stability discount off fair rate)',
  },
  {
    id: 'q6_existing_emis',
    isMust: true,
    title: 'What are your total existing monthly EMI obligations?',
    subtitle: 'Include personal loans, vehicle EMIs, home loans, and minimum credit card dues.',
    field: 'existingEmiTotal',
    category: 'obligations',
    type: 'number',
    min: 0,
    max: 1000000,
    step: 500,
    placeholder: 'e.g. 14000',
    suffix: 'INR / month',
    isVisible: () => true,
    whyAsked: 'Existing EMIs are subtracted directly from your monthly debt ceiling.',
    whatItMoves: 'O2 (Remaining loan sanction), O4 (Residual cashflow)',
  },
  {
    id: 'q7_essential_expenses',
    isMust: true,
    title: 'What are your monthly essential household expenses?',
    subtitle: 'Rent, groceries, school fees, utilities, and medicine. Non-negotiable costs only.',
    field: 'essentialExpenses',
    category: 'obligations',
    type: 'number',
    min: 2000,
    max: 1000000,
    step: 500,
    placeholder: 'e.g. 40000',
    suffix: 'INR / month',
    isVisible: () => true,
    whyAsked: 'Ensures that taking on a new loan leaves at least 15% of income as a safety buffer.',
    whatItMoves: 'O2 (Safe amount residual check), O4 (Stress survival buffer)',
  },
  {
    id: 'q8_age',
    isMust: true,
    title: 'What is your current age?',
    subtitle: 'Indian retail lenders require repayment before age 60 (salaried) or 65 (business).',
    field: 'age',
    category: 'core',
    type: 'number',
    min: 18,
    max: 75,
    step: 1,
    placeholder: 'e.g. 31',
    suffix: 'Years',
    isVisible: () => true,
    whyAsked: 'Caps the maximum available loan tenure so it does not extend beyond retirement.',
    whatItMoves: 'O4 (Maximum allowable tenure)',
  },
  {
    id: 'q9_credit_score',
    isMust: true,
    title: 'What is your bureau credit score (CIBIL / Experian)?',
    subtitle: 'If you have never checked or do not have a formal credit history, select Unknown.',
    field: 'creditScore',
    category: 'risk_proxies',
    type: 'radio',
    options: [
      { label: 'Excellent (750+)', value: 780, hint: 'Prime tier, lowest rates and highest multiples' },
      { label: 'Good (680 - 749)', value: 710, hint: 'Near-prime tier, standard prime spreads' },
      { label: 'Fair / Poor (< 650)', value: 620, hint: 'Subprime tier, tighter FOIR and higher pricing' },
      { label: 'Unknown / No Bureau History', value: 'unknown', hint: 'Underwritten via banking proxies and asset backing' },
    ],
    isVisible: () => true,
    whyAsked: 'Sets your risk tier, loan multiple ceiling, and fair interest rate band.',
    whatItMoves: 'O2 (Income multiple ceiling), O3 (Rate band tier positioning)',
  },

  // ---------------------------------------------------------
  // 11 ADDITIONAL / ADAPTIVE QUESTIONS (Each moves a number)
  // ---------------------------------------------------------
  {
    id: 'q10_variable_income',
    isMust: false,
    title: 'What share of your income is variable (bonuses, commissions, incentives)?',
    subtitle: 'High volatility in earnings increases repayment vulnerability during slow months.',
    field: 'variableIncomeShare',
    category: 'income',
    type: 'radio',
    options: [
      { label: 'Under 20% (Stable base income)', value: 0.10, hint: '0% stability haircut applied' },
      { label: '20% to 40% (Moderate incentives)', value: 0.30, hint: '10% haircut applied on volatile earnings' },
      { label: 'Over 40% (Predominantly incentive-driven)', value: 0.50, hint: '20% volatility haircut applied' },
    ],
    isVisible: (profile) => profile.employmentType === 'salaried' || profile.employmentType === 'self_employed_formal',
    whyAsked: 'Lenders discount highly variable earnings when computing debt service coverage.',
    whatItMoves: 'O2 (Assessed income haircut), O3 (Risk tier stability)',
  },
  {
    id: 'q11_high_cost_debt',
    isMust: false,
    title: 'Is more than 30% of your existing debt from high-cost sources (>24% APR)?',
    subtitle: 'This includes instant credit apps, rolling credit card balances, or informal local lenders.',
    field: 'hasHighCostDebt',
    category: 'obligations',
    type: 'boolean',
    isVisible: (profile) => (profile.existingEmiTotal ?? 0) > 0,
    whyAsked: 'Servicing high-cost compounding debt is a primary early warning trigger of default.',
    whatItMoves: 'O1 (Hard block trigger H3 if not consolidating)',
  },
  {
    id: 'q12_credit_card_utilisation',
    isMust: false,
    title: 'What is your average credit card limit utilisation?',
    subtitle: 'Revolving credit utilisation over 50% signals credit dependence.',
    field: 'creditCardUtilisation',
    category: 'risk_proxies',
    type: 'radio',
    options: [
      { label: 'No credit card', value: -1 },
      { label: 'Under 30% of limit (Disciplined)', value: 20 },
      { label: '30% to 60% of limit (Moderate)', value: 45 },
      { label: 'Over 60% of limit (Stretched credit)', value: 75 },
    ],
    isVisible: (profile) => profile.creditScore === 'unknown' || profile.employmentType === 'salaried',
    whyAsked: 'Serves as a reliable proxy signal for risk positioning when score is unknown or borderline.',
    whatItMoves: 'O3 (Proxy risk adjustment within rate band)',
  },
  {
    id: 'q13_recent_bounces',
    isMust: false,
    title: 'Have you had any bounced EMI, cheque, or auto-debit in the last 12 months?',
    subtitle: 'Recent bank returns are heavily weighted by NBFC and bank underwriting algorithms.',
    field: 'hasBounceInLast12Months',
    category: 'risk_proxies',
    type: 'radio',
    options: [
      { label: 'None (Clean payment track record)', value: false, hint: 'No penalty' },
      { label: 'Yes, within the last 3 months', value: true, hint: 'Hard block on unsecured consumption' },
      { label: 'Yes, 4 to 12 months ago', value: true, hint: 'Minus 10 percentage points from safe FOIR' },
    ],
    isVisible: () => true,
    whyAsked: 'A recent bounce indicates active liquidity stress.',
    whatItMoves: 'O1 (Hard block trigger H2), O2 (Minus 10 points to Safe FOIR cap)',
  },
  {
    id: 'q14_savings_buffer',
    isMust: false,
    title: 'How many months of essential living expenses do you hold in liquid savings?',
    subtitle: 'Bank deposits, mutual funds, or liquid cash available immediately without borrowing.',
    field: 'savingsBufferMonths',
    category: 'assets',
    type: 'radio',
    options: [
      { label: 'Zero / Under 1 month (Living paycheck to paycheck)', value: 0.5 },
      { label: '1 to 3 months of expenses', value: 2 },
      { label: '4 to 6 months of expenses (Resilient cushion)', value: 5 },
      { label: 'Over 6 months of expenses (Substantial reserves)', value: 8 },
    ],
    isVisible: () => true,
    whyAsked: 'Determines whether a borrower can survive a 25% income shock or medical emergency.',
    whatItMoves: 'O1 (Hard block trigger H4 for informal), O4 (Stress resilience)',
  },
  {
    id: 'q15_collateral',
    isMust: false,
    title: 'Do you have unencumbered tangible collateral you could pledge?',
    subtitle: 'Note: Vehicle hypothecation is not treated as strong collateral due to rapid depreciation.',
    field: 'collateralType',
    category: 'assets',
    type: 'select',
    options: [
      { label: 'None (Unsecured loan)', value: 'none' },
      { label: 'Residential or Commercial Property (Unencumbered)', value: 'property', hint: 'LTV 50-60%, lowest rates' },
      { label: 'Physical Gold / Sovereign Gold Bonds', value: 'gold', hint: 'Regulatory LTV up to 75%' },
      { label: 'Bank Fixed Deposit', value: 'fixed_deposit', hint: 'LTV up to 85%' },
      { label: 'Vehicle Hypothecation', value: 'vehicle', hint: 'Evaluated as unsecured for hard blocks' },
    ],
    isVisible: () => true,
    whyAsked: 'Pledging strong assets unlocks secured product spreads and +5% to lender FOIR cap.',
    whatItMoves: 'O2 (Unlocks LTV calculation, lifts FOIR), O3 (Routes to secured product band)',
  },
  {
    id: 'q16_co_applicant',
    isMust: false,
    title: 'Can an earning family member join as a formal co-applicant?',
    subtitle: 'Combining household income can bridge the gap if your individual capacity falls short.',
    field: 'hasCoApplicant',
    category: 'income',
    type: 'boolean',
    isVisible: () => true,
    whyAsked: 'Household underwriting allows higher total sanctions for home or business growth.',
    whatItMoves: 'O2 (Surfaces household eligibility option to bridge ticket gaps)',
  },
  {
    id: 'q17_lump_sum_expenses',
    isMust: false,
    title: 'Do you anticipate any large mandatory expenditure in the next 6 to 12 months?',
    subtitle: 'Annual school admissions, major insurance premiums, or scheduled home maintenance.',
    field: 'upcomingLumpSumExpenseIn12m',
    category: 'obligations',
    type: 'number',
    min: 0,
    max: 2000000,
    step: 5000,
    placeholder: 'e.g. 50000 (or 0 if none)',
    suffix: 'INR',
    isVisible: () => true,
    whyAsked: 'An EMI that looks safe on regular months can trigger default when a seasonal expense hits.',
    whatItMoves: 'O4 (Subtracted from safe residual monthly buffer)',
  },
  {
    id: 'q18_productive_return',
    isMust: false,
    title: 'If this loan is for business or income generation, what extra monthly income will it create?',
    subtitle: 'A loan that pays for itself with verifiable returns is a materially different risk.',
    field: 'expectedMonthlyReturn',
    category: 'core',
    type: 'number',
    min: 0,
    max: 500000,
    step: 1000,
    placeholder: 'e.g. 15000 (or 0 if consumer loan)',
    suffix: 'INR / month',
    isVisible: (profile) =>
      profile.purpose === 'business_stock_equipment' ||
      profile.purpose === 'commercial_vehicle' ||
      profile.purpose === 'education',
    whyAsked: 'Productive loans with verified positive cashflows can lift soft caution ceilings.',
    whatItMoves: 'O1 (Lifts soft caution S3 on productive borrowing)',
  },
  {
    id: 'q19_existing_quote',
    isMust: false,
    title: 'Have you already received a loan offer or quote from a bank or NBFC?',
    subtitle: 'We will compare their proposed rate and fees directly against your fair market band.',
    field: 'existingLenderQuote',
    category: 'quotes',
    type: 'number',
    min: 5,
    max: 45,
    step: 0.25,
    placeholder: 'Offered rate % (e.g. 15.5)',
    suffix: '% p.a.',
    isVisible: () => true,
    whyAsked: 'Provides an immediate benchmark comparison for your bank counter negotiation.',
    whatItMoves: 'Negotiation Card (Calculates exact difference from fair market band)',
  },
  {
    id: 'q20_informal_digital_footprint',
    isMust: false,
    title: 'Do you receive regular digital payments (UPI QR / Bank Transfer) for your trade?',
    subtitle: 'Transaction history through UPI QR codes is used by modern lenders as cashflow proof.',
    field: 'informalDigitalPaymentHistory',
    category: 'risk_proxies',
    type: 'boolean',
    isVisible: (profile) => profile.employmentType === 'informal_gig',
    whyAsked: 'UPI transaction density is the primary substitute for formal ITR documentation.',
    whatItMoves: 'O2 (Reduces informal haircut severity), O3 (Positioning within informal band)',
  },
];
